#define STB_IMAGE_IMPLEMENTATION
#define STBI_ONLY_JPEG
#define STB_IMAGE_WRITE_IMPLEMENTATION
#define BICUBIC_IMPLEMENTATION
#define GAUSS_IMPLEMENTATION
#include <stb/stb_image.h>
#include <stb/stb_image_write.h>
#include "bicubic.h"
#include "gauss.h"
